name: HPFL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - addict=2.4.0
  - aiohttp=3.7.0
  - antlr-python-runtime=4.8
  - antlr4-python3-runtime=4.8
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=3.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=21.4b2
  - blas=1.0
  - bleach=5.0.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cffi=1.15.0
  - chardet=3.0.4
  - click=8.1.3
  - cloudpickle=2.0.0
  - commonmark=0.9.1
  - cryptography=35.0.0
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dill=0.3.5.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.2.10
  - ffmpeg=4.3
  - flit-core=3.7.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - funcy=1.17
  - future=0.18.2
  - gh=2.14.4
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth-oauthlib=0.4.6
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_resources=5.9.0
  - intel-openmp=2021.4.0
  - iopath=0.1.9
  - ipdb=0.13.9
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - isort=5.10.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.5.1
  - jupyter=1.0.0
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - loguru=0.6.0
  - lxml=4.8.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - mypy_extensions=0.4.3
  - natsort=8.1.0
  - nbclient=0.6.3
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.4.11
  - oauthlib=3.2.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.9.0
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - portalocker=2.5.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pycparser=2.21
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.8
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - qt=5.9.7
  - qtconsole=5.3.1
  - qtconsole-base=5.3.1
  - qtpy=2.1.0
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - send2trash=1.8.0
  - sip=4.19.13
  - six=1.16.0
  - smmap=3.0.5
  - soupsieve=2.3.2.post1
  - sqlite=3.38.3
  - stack_data=0.3.0
  - tabulate=0.8.10
  - termcolor=1.1.0
  - terminado=0.15.0
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tk=8.6.11
  - toml=0.10.2
  - torchaudio=0.12.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typed-ast=1.4.3
  - typish=1.9.3
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - alfred==0.3
    - alfred-py==2.10.6
    - astroid==2.11.7
    - attributee==0.1.7
    - basicsr==1.4.2
    - bidict==0.22.0
    - cachetools==5.1.0
    - certifi==2022.6.15
    - charset-normalizer==2.1.0
    - colorama==0.4.5
    - coloredlogs==15.0.1
    - contourpy==1.0.5
    - cvxpy==1.3.2
    - cython==0.29.28
    - dataclasses==0.6
    - debugpy==1.6.0
    - dominate==2.6.0
    - easydict==1.9
    - ecos==2.0.12
    - facexlib==0.2.3
    - faiss-gpu==1.7.2
    - filterpy==1.4.5
    - flatbuffers==2.0
    - fonttools==4.33.3
    - google-auth==2.9.1
    - grpcio==1.46.1
    - gtrending==0.3.6
    - h5py==3.7.0
    - humanfriendly==10.0
    - hydra-core==1.1.2
    - imageio==2.20.0
    - jpeg4py==0.1.4
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsons==1.6.3
    - jupyter-client==7.3.1
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.7.1
    - llvmlite==0.38.1
    - lmdb==1.3.0
    - markdown==3.4.1
    - matplotlib==3.5.3
    - mpmath==1.2.1
    - networkx==2.8.5
    - numba==0.55.2
    - numpy==1.22.4
    - omegaconf==2.1.2
    - onnx==1.11.0
    - onnx-simplifier==0.3.10
    - onnxoptimizer==0.2.7
    - onnxruntime==1.12.0
    - onnxruntime-gpu==1.11.1
    - opencv-python==4.5.5.64
    - ordered-set==4.1.0
    - osqp==0.6.3
    - pandas==1.4.3
    - pascal-voc-writer==0.1.4
    - phx-class-registry==3.0.5
    - pillow==9.2.0
    - promise==2.3
    - protobuf==3.20.1
    - pyasn1-modules==0.2.8
    - pylatex==1.4.1
    - pyquaternion==0.9.9
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyzmq==23.2.0
    - qdldl==0.1.7.post0
    - regex==2022.7.25
    - require==0.1.1
    - rich==12.5.1
    - scikit-image==0.19.3
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - scs==3.2.3
    - sentry-sdk==1.9.3
    - setproctitle==1.3.1
    - setuptools==68.0.0
    - shortuuid==1.0.9
    - sklearn==0.0
    - sympy==1.10.1
    - tb-nightly==2.9.0a20220401
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tifffile==2022.5.4
    - tikzplotlib==0.10.1
    - torch==1.12.0
    - torchfile==0.1.0
    - torchscan==0.1.2
    - torchvision==0.13.0
    - typing-extensions==4.3.0
    - visdom==0.1.8.9
    - vot-toolkit==0.5.3
    - vot-trax==3.0.3
    - wandb==0.13.1
    - webcolors==1.11.1
    - websocket-client==1.4.1
    - werkzeug==2.0.3
    - wrapt==1.14.1
    - xdg==5.1.1
    - yapf==0.32.0
    - zipp==3.7.0
